# Generated by Django 4.1.1 on 2022-09-19 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_prospectus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('father_occupation', models.CharField(max_length=200)),
                ('father_number', models.CharField(max_length=17)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_occupation', models.CharField(max_length=200)),
                ('mother_number', models.CharField(max_length=17)),
                ('garduian_name', models.CharField(max_length=200)),
                ('garduian_number', models.CharField(max_length=17)),
                ('nationality', models.CharField(max_length=17)),
                ('dob', models.CharField(max_length=17)),
                ('gender', models.CharField(max_length=17)),
                ('blood_group', models.CharField(max_length=17)),
                ('caste', models.CharField(max_length=17)),
                ('religion', models.CharField(max_length=17)),
                ('hslc_board', models.CharField(default=' ', max_length=17)),
                ('hslc_passing_year', models.CharField(default=' ', max_length=17)),
                ('hslc_reg', models.CharField(default=' ', max_length=70)),
                ('hslc_roll', models.CharField(default=' ', max_length=17)),
                ('hslc_total_marks', models.CharField(default=' ', max_length=17)),
                ('hslc_marks', models.CharField(default=' ', max_length=17)),
                ('hslc_percentage', models.CharField(default=' ', max_length=17)),
                ('hslc_school', models.CharField(default=' ', max_length=17)),
                ('hsslc_board', models.CharField(default=' ', max_length=17)),
                ('hsslc_stream', models.CharField(default=' ', max_length=17)),
                ('hsslc_passing_year', models.CharField(default=' ', max_length=17)),
                ('hsslc_reg', models.CharField(default=' ', max_length=70)),
                ('hsslc_roll', models.CharField(default=' ', max_length=70)),
                ('hsslc_percentage', models.CharField(default=' ', max_length=17)),
                ('hsslc_school', models.CharField(default=' ', max_length=17)),
                ('graduation_course_name', models.CharField(default=' ', max_length=50)),
                ('graduation_board', models.CharField(default=' ', max_length=50)),
                ('graduation_course_type', models.CharField(default=' ', max_length=17)),
                ('graduation_year', models.CharField(default=' ', max_length=17)),
                ('graduation_reg', models.CharField(default=' ', max_length=70)),
                ('graduation_roll', models.CharField(default=' ', max_length=70)),
                ('graduation_total_marks', models.CharField(default=' ', max_length=17)),
                ('graduation_marks', models.CharField(default=' ', max_length=17)),
                ('graduation_percentage', models.CharField(default=' ', max_length=17)),
                ('graduation_university', models.CharField(default=' ', max_length=50)),
                ('post_graduation_course_name', models.CharField(default=' ', max_length=50)),
                ('post_graduation_board', models.CharField(default=' ', max_length=50)),
                ('post_graduation_course_type', models.CharField(default=' ', max_length=17)),
                ('post_graduation_year', models.CharField(default=' ', max_length=17)),
                ('post_graduation_reg', models.CharField(default=' ', max_length=70)),
                ('post_graduation_roll', models.CharField(default=' ', max_length=70)),
                ('post_graduation_total_marks', models.CharField(default=' ', max_length=17)),
                ('post_graduation_marks', models.CharField(default=' ', max_length=17)),
                ('post_graduation_percentage', models.CharField(default=' ', max_length=17)),
                ('post_graduation_university', models.CharField(default=' ', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
