# Generated by Django 4.1.1 on 2022-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_admissionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_board',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_course_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_course_type',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_marks',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_percentage',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_reg',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_roll',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_total_marks',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_university',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='graduation_year',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_board',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_marks',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_passing_year',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_percentage',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_reg',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_roll',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_school',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hslc_total_marks',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hsslc_board',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hsslc_passing_year',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hsslc_percentage',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hsslc_reg',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hsslc_roll',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hsslc_school',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='hsslc_stream',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_board',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_course_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_course_type',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_marks',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_percentage',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_reg',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_roll',
            field=models.CharField(blank=True, default=' ', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_total_marks',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_university',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_graduation_year',
            field=models.CharField(blank=True, default=' ', max_length=17, null=True),
        ),
    ]
