# Generated by Django 4.1.1 on 2022-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_admissionform_graduation_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='is_verified',
            field=models.CharField(blank=True, default='False', max_length=10, null=True),
        ),
    ]
