# Generated by Django 4.0 on 2022-10-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_admissionform_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hslc_doc', models.ImageField(upload_to='AdmissionDocument')),
                ('hslc_marksheet', models.ImageField(upload_to='AdmissionDocument')),
                ('hsslc_doc', models.ImageField(upload_to='AdmissionDocument')),
                ('hsslc_marksheet', models.ImageField(upload_to='AdmissionDocument')),
                ('caste_certificate', models.ImageField(upload_to='AdmissionDocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'AdmissionDocument',
                'verbose_name_plural': 'AdmissionDocuments',
            },
        ),
    ]
