# Generated by Django 4.1.1 on 2022-11-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='is_verified',
            field=models.CharField(choices=[(True, 'True'), (False, 'False')], default=True, max_length=2),
        ),
    ]
