# Generated by Django 4.1.1 on 2022-11-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_admissionform_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='course',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
    ]
