# Generated by Django 4.1.1 on 2022-11-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_admissionform_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='is_verified',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=10),
        ),
    ]
