# Generated by Django 4.1.1 on 2022-11-10 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_admissionform_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('date_field', models.DateField(default=django.utils.timezone.now)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
