# Generated by Django 4.1.1 on 2022-11-12 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_notice_date_field_alter_notice_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
