# Generated by Django 4.1.1 on 2022-11-14 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_notice_date_field_alter_notice_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('photo', models.ImageField(upload_to='teacher')),
                ('employee_id', models.CharField(max_length=60, verbose_name='Employee ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Designation')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=100, verbose_name='Email ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=10, verbose_name='Employee Status')),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
