# Generated by Django 4.1.1 on 2022-11-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_teacher_alter_notice_date_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
